# Source: https://github.com/lowlighter/metrics#-documentation
name: Update Github Base

on:
  # runs every day at 02:00
  schedule: [{ cron: "0 2 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics-gh-base.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          base: header, activity, community, repositories, metadata
