# Source: https://github.com/lowlighter/metrics#-documentation
name: Update GitHub Full Metrics

on:
  # runs every day at 05:00
  # schedule: [{ cron: "0 5 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics-gh-full-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: semanticdata
          template: classic
          base: activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: America/Chicago
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_limit: 8
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_notable: yes
          # plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_posts: yes
          plugin_posts_covers: yes
          plugin_posts_descriptions: yes
          plugin_posts_limit: 4
          plugin_posts_source: dev.to
          plugin_posts_user: semanticdata
          plugin_repositories: yes
          plugin_repositories_featured: semanticdata, mabuya
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_starred: 2
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://database.bearblog.dev/feed/?q=posts
          plugin_stars: yes
          plugin_stars_limit: 4
