# Source: https://github.com/lowlighter/metrics#-documentation
name: Update GitHub Recent activity

on:
  # runs every day at 02:30
  schedule: [{ cron: "30 2 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Recent activity
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics-gh-recent-activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 10 # default is 5
          plugin_activity_days: 14  # default is 14
          plugin_activity_filter: issue, pr, release, review, fork, star
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes
          # opts: [push|issue|pr|ref/create|ref/delete|release|review|comment|wiki|fork|star|public|member]
