# Source: https://github.com/lowlighter/metrics#-documentation
name: Markdown Template (test)

on:
  # runs every day at 00:00
  # schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics-markdown.md
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: semanticdata
          template: markdown
          config_output: markdown
          markdown_cache: .cache
          markdown: >-
            https://raw.githubusercontent.com/semanticdata/metrics/main/metrics-markdown-source.md
          base: ""
          
          plugin_rss: yes
          plugin_rss_source: https://database.bearblog.dev/feed/?q=posts
          plugin_languages: yes
