# Source: https://github.com/lowlighter/metrics#-documentation
name: Update Spotify Music (playlist)

on:
  # runs every day at 06:25
  # schedule: [{ cron: "25 6 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Spotify - Random track from playlist
      uses: lowlighter/metrics@latest
      with:
        filename: svg/metrics-music-spotify.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_music: yes
        plugin_music_playlist: https://open.spotify.com/embed/playlist/43yhgA1Y05nyRGL8QeRUFO
        plugin_music_provider: spotify
        plugin_music_mode: recent # top, recent
        plugin_music_token: ${{ secrets.REFRESH_TOKEN }}
        plugin_music_limit: 2
        plugin_music_time_range: short # short, long
        plugin_music_top_type: tracks # artists, tracks
  
