# Source: https://github.com/lowlighter/metrics#-documentation
name: PageSpeed Results

on:
  schedule: [{cron: "0 5 * * *"}]
  workflow_dispatch:
  # push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: semanticdata
          template: classic
          base: ""
          config_timezone: America/Chicago
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://miguelpimentel.do/
