# Source: https://github.com/lowlighter/metrics#-documentation
name: Update Blog entries

on:
  # runs every day at 01:00
  schedule: [{ cron: "0 1 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics-rss-blog.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: semanticdata
          template: classic
          base: ""
          plugin_rss: yes
          plugin_rss_source: https://database.bearblog.dev/feed/?q=posts
          plugin_rss_limit: 4
