# Source: https://github.com/lowlighter/metrics#-documentation
name: Update (RSS) Tutorials

on:
  # runs every day at 23:30
  # schedule: [{ cron: "30 23 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics-rss-tutorials.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: semanticdata
          template: classic
          base: ""
          plugin_rss: yes
          plugin_rss_source: https://database.bearblog.dev/feed/?q=tutorials
          plugin_rss_limit: 4
