# Source: https://github.com/lowlighter/metrics#-documentation
name: Update Tutorials

on:
  schedule: [{ cron: "0 4 * * *" }]
  workflow_dispatch:
  # push: {branches: ["master", "main"]}

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.rss.tutorials.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: semanticdata
          template: classic
          base: ""
          plugin_rss: yes
          plugin_rss_source: https://database.bearblog.dev/feed/?q=tutorials
          plugin_rss_limit: 4
