# Source: https://github.com/lowlighter/metrics#-documentation
name: Update (RSS) Dev.to entries

on:
  # runs every day at 00:30
  schedule: [{ cron: "30 0 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics-rss-dev.to.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          base: ""
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_posts_limit: 3
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes
          plugin_posts_user: semanticdata
