# Source: https://github.com/lowlighter/metrics#-documentation
name: Update Spotify - Recently Played (Artists)

on:
  # runs every day at 06:25
  # schedule: [{ cron: "25 6 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Spotify - Recently Played (Artists)
      uses: lowlighter/metrics@latest
      with:
        filename: svg/metrics-spotify-recently-played-artists.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_music: yes
        plugin_music_provider: spotify
        plugin_music_token: ${{ secrets.SPOTIFY_SECRETS }}
        plugin_music_mode: recent      # opts: [playlist|top|recent]
        plugin_music_limit: 8          # opts: [1-100]
        plugin_music_time_range: short # opts: [short|medium|long]
        plugin_music_top_type: artists # opts: [artists|tracks]
        plugin_music_played_at: yes    # opts: [yes|no]
        plugin_music_playlist: https://open.spotify.com/embed/playlist/43yhgA1Y05nyRGL8QeRUFO
