# Source: https://github.com/lowlighter/metrics#-documentation
name: Update Spotify - Recently Played

on:
  # runs every day at 06:25
  # schedule: [{ cron: "25 6 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Spotify - Recently Played
      uses: lowlighter/metrics@latest
      with:
        filename: svg/metrics-spotify-recently-played.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_music: yes
        plugin_music_provider: spotify
        plugin_music_token: ${{ secrets.SPOTIFY_SECRETS }}
        plugin_music_mode: recent
        plugin_music_limit: 10
        plugin_music_time_range: short
        plugin_music_played_at: yes
