# Source: https://github.com/lowlighter/metrics#-documentation
name: Update Spotify - Playlist

on:
  # runs every day at 06:55
  # schedule: [{ cron: "55 6 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Spotify - Playlist
      uses: lowlighter/metrics@latest
      with:
        filename: svg/metrics-spotify-playlist.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_music: yes
        plugin_music_provider: spotify
        plugin_music_token: ${{ secrets.SPOTIFY_SECRETS }}
        plugin_music_mode: playlist
        # plugin_music_playlist: "https://open.spotify.com/embed/playlist/43yhgA1Y05nyRGL8QeRUFO"
        plugin_music_playlist: "https://open.spotify.com/embed/playlist/02anS0I93G91oM6AERsBGd?utm_source=generator"
