# Source: https://github.com/lowlighter/metrics#-documentation
name: Update ForgetulNotes.com PageSpeed results

on:
  # runs every day at 23:15
  schedule: [{ cron: "15 23 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics-web-pagespeed-2.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: semanticdata
          template: classic
          base: ""
          config_timezone: America/Chicago
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://forgetulnotes.com/
