# Source: https://github.com/lowlighter/metrics#-documentation
name: Website Screenshot

on:
  # runs every day at 22:30
  schedule: [{ cron: "30 22 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics-screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics-web-screenshot.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: Website Screenshot
          plugin_screenshot_url: https://miguelpimentel.do
