# Source: https://github.com/lowlighter/metrics#-documentation
name: Update Website Screenshot

on:
  # runs every day at 22:30
  # schedule: [{ cron: "30 22 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics-screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics-web-screenshot.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: Screenshot - MiguelPimentel.do
          plugin_screenshot_url: https://miguelpimentel.do
          plugin_screenshot_selector: body # default
          plugin_screenshot_background: no # changed
          plugin_screenshot_wait:        0 # default
          plugin_screenshot_viewport: '{"width": 512, "height": 512}' # default: 1280x1280
