name: Website Screenshot

on:
  schedule: [{ cron: "0 2 * * *" }]
  workflow_dispatch:
  # push: {branches: ["master", "main"]}

permissions:
  contents: write

jobs:
  github-metrics-screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.screenshot.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: Website Screenshot
          plugin_screenshot_url: https://miguelpimentel.do
