# Source: https://github.com/lowlighter/metrics#-documentation
name: Update PageSpeed results

on:
  schedule: [{ cron: "0 5 * * *" }]
  workflow_dispatch:
  # push: {branches: ["master", "main"]}

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: semanticdata
          template: classic
          base: ""
          config_timezone: America/Chicago
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://miguelpimentel.do/
